In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv(r'market_data (1).csv')

In [3]:
data.head()

youtube  facebook  newspaper  sales
0    84.72     19.20      48.96  12.60
1   351.48     33.96      51.84  25.68
2   135.48     20.88      46.32  14.28
3   116.64      1.80      36.00  11.52
4   318.72     24.00       0.36  20.88

In [4]:
data.tail()

youtube  facebook  newspaper  sales
166    45.84      4.44      16.56   9.12
167   113.04      5.88       9.72  11.64
168   212.40     11.16       7.68  15.36
169   340.32     50.40      79.44  30.60
170   278.52     10.32      10.44  16.08

In [5]:
data.shape

(171, 4)

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 171 entries, 0 to 170
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   youtube    171 non-null    float64
 1   facebook   171 non-null    float64
 2   newspaper  171 non-null    float64
 3   sales      171 non-null    float64
dtypes: float64(4)
memory usage: 5.5 KB


In [7]:
data.describe().T

count        mean         std   min    25%     50%     75%     max
youtube    171.0  178.021053  102.449597  0.84  91.08  179.76  262.98  355.68
facebook   171.0   27.671579   17.913532  0.00  11.70   26.76   43.68   59.52
newspaper  171.0   35.240000   24.902918  0.36  13.74   31.08   50.88  121.08
sales      171.0   16.922807    6.314608  1.92  12.54   15.48   20.82   32.40

In [8]:
data.corr()

youtube  facebook  newspaper     sales
youtube    1.000000  0.086538   0.110759  0.782030
facebook   0.086538  1.000000   0.293425  0.602918
newspaper  0.110759  0.293425   1.000000  0.254987
sales      0.782030  0.602918   0.254987  1.000000

In [9]:
X = data.drop('sales', axis=1)

In [10]:
X.head()

youtube  facebook  newspaper
0    84.72     19.20      48.96
1   351.48     33.96      51.84
2   135.48     20.88      46.32
3   116.64      1.80      36.00
4   318.72     24.00       0.36

In [11]:
type(X)

pandas.core.frame.DataFrame

In [12]:
y = data['sales']

In [13]:
y.head()

0    12.60
1    25.68
2    14.28
3    11.52
4    20.88
Name: sales, dtype: float64

In [14]:
type(y)

pandas.core.series.Series

In [15]:
X.values

array([[ 84.72,  19.2 ,  48.96],
       [351.48,  33.96,  51.84],
       [135.48,  20.88,  46.32],
       [116.64,   1.8 ,  36.  ],
       [318.72,  24.  ,   0.36],
       [114.84,   1.68,   8.88],
       [348.84,   4.92,  10.2 ],
       [320.28,  52.56,   6.  ],
       [ 89.64,  59.28,  54.84],
       [ 51.72,  32.04,  42.12],
       [273.6 ,  45.24,  38.4 ],
       [243.  ,  26.76,  37.92],
       [212.4 ,  40.08,  46.44],
       [352.32,  33.24,   2.16],
       [248.28,  10.08,  31.68],
       [ 30.12,  30.84,  51.96],
       [210.12,  27.  ,  37.8 ],
       [107.64,  11.88,  42.84],
       [287.88,  49.8 ,  22.2 ],
       [272.64,  18.96,  59.88],
       [ 80.28,  14.04,  44.16],
       [239.76,   3.72,  41.52],
       [120.48,  11.52,   4.32],
       [259.68,  50.04,  47.52],
       [219.12,  55.44,  70.44],
       [315.24,  34.56,  19.08],
       [238.68,  59.28,  72.  ],
       [  8.76,  33.72,  49.68],
       [163.44,  23.04,  19.92],
       [252.96,  59.52,  45.24],
       [25

In [16]:
X_arr = X.to_numpy()

In [17]:
X_arr

array([[ 84.72,  19.2 ,  48.96],
       [351.48,  33.96,  51.84],
       [135.48,  20.88,  46.32],
       [116.64,   1.8 ,  36.  ],
       [318.72,  24.  ,   0.36],
       [114.84,   1.68,   8.88],
       [348.84,   4.92,  10.2 ],
       [320.28,  52.56,   6.  ],
       [ 89.64,  59.28,  54.84],
       [ 51.72,  32.04,  42.12],
       [273.6 ,  45.24,  38.4 ],
       [243.  ,  26.76,  37.92],
       [212.4 ,  40.08,  46.44],
       [352.32,  33.24,   2.16],
       [248.28,  10.08,  31.68],
       [ 30.12,  30.84,  51.96],
       [210.12,  27.  ,  37.8 ],
       [107.64,  11.88,  42.84],
       [287.88,  49.8 ,  22.2 ],
       [272.64,  18.96,  59.88],
       [ 80.28,  14.04,  44.16],
       [239.76,   3.72,  41.52],
       [120.48,  11.52,   4.32],
       [259.68,  50.04,  47.52],
       [219.12,  55.44,  70.44],
       [315.24,  34.56,  19.08],
       [238.68,  59.28,  72.  ],
       [  8.76,  33.72,  49.68],
       [163.44,  23.04,  19.92],
       [252.96,  59.52,  45.24],
       [25

In [18]:
print(X.values == X_arr)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True

In [19]:
x1 = data['youtube']

In [20]:
len(x1)

171

In [21]:
len(data)

171

In [22]:
n = len(data)

In [23]:
theta_0 = np.ones((n, 1))

In [24]:
theta_0

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],

In [25]:
X_arr = np.append(theta_0, X_arr, axis=1)

In [26]:
X_arr

array([[  1.  ,  84.72,  19.2 ,  48.96],
       [  1.  , 351.48,  33.96,  51.84],
       [  1.  , 135.48,  20.88,  46.32],
       [  1.  , 116.64,   1.8 ,  36.  ],
       [  1.  , 318.72,  24.  ,   0.36],
       [  1.  , 114.84,   1.68,   8.88],
       [  1.  , 348.84,   4.92,  10.2 ],
       [  1.  , 320.28,  52.56,   6.  ],
       [  1.  ,  89.64,  59.28,  54.84],
       [  1.  ,  51.72,  32.04,  42.12],
       [  1.  , 273.6 ,  45.24,  38.4 ],
       [  1.  , 243.  ,  26.76,  37.92],
       [  1.  , 212.4 ,  40.08,  46.44],
       [  1.  , 352.32,  33.24,   2.16],
       [  1.  , 248.28,  10.08,  31.68],
       [  1.  ,  30.12,  30.84,  51.96],
       [  1.  , 210.12,  27.  ,  37.8 ],
       [  1.  , 107.64,  11.88,  42.84],
       [  1.  , 287.88,  49.8 ,  22.2 ],
       [  1.  , 272.64,  18.96,  59.88],
       [  1.  ,  80.28,  14.04,  44.16],
       [  1.  , 239.76,   3.72,  41.52],
       [  1.  , 120.48,  11.52,   4.32],
       [  1.  , 259.68,  50.04,  47.52],
       [  1.  , 

In [27]:
X_tran = np.transpose(X_arr)

In [28]:
X_tran

array([[  1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,
          1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,
          1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,
          1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,
          1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,
          1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,
          1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,
          1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,
          1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,
          1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,
          1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,
          1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,
          1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,
          1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  , 

In [29]:
X_trans_dot_x =  X_tran.dot(X_arr)

In [30]:
X_trans_dot_x 

array([[1.71000000e+02, 3.04416000e+04, 4.73184000e+03, 6.02604000e+03],
       [3.04416000e+04, 7.20355208e+06, 8.69366232e+05, 1.12080054e+06],
       [4.73184000e+03, 8.69366232e+05, 1.85489568e+05, 1.89002506e+05],
       [6.02604000e+03, 1.12080054e+06, 1.89002506e+05, 3.17784053e+05]])

In [31]:
term_1 = np.linalg.inv(X_trans_dot_x)

In [32]:
term_1

array([[ 3.95364413e-02, -8.83018573e-05, -3.75982708e-04,
        -2.14666950e-04],
       [-8.83018573e-05,  5.69244048e-07, -1.92501263e-07,
        -2.18750098e-07],
       [-3.75982708e-04, -1.92501263e-07,  2.01231733e-05,
        -4.15970472e-06],
       [-2.14666950e-04, -2.18750098e-07, -4.15970472e-06,
         1.04629589e-05]])

In [33]:
term_2 = X_tran.dot(y)

In [34]:
term_2

array([  2893.8   , 601163.3664,  91670.0544, 108794.0448])

In [35]:
thetas = term_1.dot(term_2)

In [36]:
thetas

array([3.50587099, 0.04523544, 0.18839783, 0.00427949])

In [37]:
bias = thetas[0]
weight_1 = thetas[1]
weight_2 = thetas[2]
weight_3 = thetas[3]

In [38]:
def predict(bias, weight_1, weight_2, weight_3, x_1, x_2, x_3):
    predicted_value = bias + (x_1 * weight_1) + (x_2 * weight_2) + (x_3 * weight_3)
    return predicted_value

In [39]:
x_1 = float(input('enter the spend on YouTupe: '))
x_2 = float(input('enter the spend on FaceBook: '))
x_3 = float(input('enter the spend on NewsPaper: '))

enter the spend on YouTupe: 84.72
enter the spend on FaceBook: 19.20
enter the spend on NewsPaper: 48.96


In [40]:
print('Predicted Sales is: {0}'.format(predict(bias, weight_1, weight_2, weight_3, x_1, x_2, x_3)))

Predicted Sales is: 11.164980014404884


In [41]:
X['predicted_sales'] = X.apply(lambda row: predict(bias, weight_1, weight_2, weight_3, row['youtube'], row['facebook'], row['newspaper']), axis=1)

In [42]:
data = pd.concat([data, X['predicted_sales']], axis=1)

In [43]:
data

youtube  facebook  newspaper  sales  predicted_sales
0      84.72     19.20      48.96  12.60        11.164980
1     351.48     33.96      51.84  25.68        26.025064
2     135.48     20.88      46.32  14.28        13.766342
3     116.64      1.80      36.00  11.52         9.275311
4     318.72     24.00       0.36  20.88        22.446400
..       ...       ...        ...    ...              ...
166    45.84      4.44      16.56   9.12         6.486818
167   113.04      5.88       9.72  11.64         9.768662
168   212.40     11.16       7.68  15.36        15.249266
169   340.32     50.40      79.44  30.60        28.735611
170   278.52     10.32      10.44  16.08        18.093790

[171 rows x 5 columns]

In [44]:
data['error'] = abs(data['sales'] - data['predicted_sales'])

In [45]:
data

youtube  facebook  newspaper  sales  predicted_sales     error
0      84.72     19.20      48.96  12.60        11.164980  1.435020
1     351.48     33.96      51.84  25.68        26.025064  0.345064
2     135.48     20.88      46.32  14.28        13.766342  0.513658
3     116.64      1.80      36.00  11.52         9.275311  2.244689
4     318.72     24.00       0.36  20.88        22.446400  1.566400
..       ...       ...        ...    ...              ...       ...
166    45.84      4.44      16.56   9.12         6.486818  2.633182
167   113.04      5.88       9.72  11.64         9.768662  1.871338
168   212.40     11.16       7.68  15.36        15.249266  0.110734
169   340.32     50.40      79.44  30.60        28.735611  1.864389
170   278.52     10.32      10.44  16.08        18.093790  2.013790

[171 rows x 6 columns]